# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "minifashion-app"
client_id = "f8bdf8ae3030c5594f19af505674433b"
application_url = "https://golf-inn-recommends-tried.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = [
  "write_products", 
  "read_customers",
  "read_inventory",
  "read_orders",
  "read_products",
  "read_users",
  "read_all_orders"
]

[auth]
redirect_urls = [
  "https://golf-inn-recommends-tried.trycloudflare.com/auth/callback",
  "https://golf-inn-recommends-tried.trycloudflare.com/auth/shopify/callback",
  "https://golf-inn-recommends-tried.trycloudflare.com/api/auth/callback",
  "https://golf-inn-recommends-tried.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-71eef196.myshopify.com"
