# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Recommend Me!"
client_id = "f8bdf8ae3030c5594f19af505674433b"
<<<<<<< HEAD
application_url = "https://largest-renewable-zealand-mia.trycloudflare.com"
=======
application_url = "https://prisoner-certification-rick-loves.trycloudflare.com"
>>>>>>> 1fb1492f0ea5a3b4c26f300d48b82df69b4cc2a8
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,read_all_orders,read_product_listings"

[auth]
redirect_urls = [
  "https://prisoner-certification-rick-loves.trycloudflare.com/auth/callback",
  "https://prisoner-certification-rick-loves.trycloudflare.com/auth/shopify/callback",
  "https://prisoner-certification-rick-loves.trycloudflare.com/api/auth/callback",
  "https://prisoner-certification-rick-loves.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-71eef196.myshopify.com"
