# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Recommend Me!"
client_id = "f8bdf8ae3030c5594f19af505674433b"
application_url = "https://computed-cliff-securities-ongoing.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products,read_all_orders,read_product_listings"

[auth]
redirect_urls = [
  "https://computed-cliff-securities-ongoing.trycloudflare.com/auth/callback",
  "https://computed-cliff-securities-ongoing.trycloudflare.com/auth/shopify/callback",
  "https://computed-cliff-securities-ongoing.trycloudflare.com/api/auth/callback",
  "https://computed-cliff-securities-ongoing.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-71eef196.myshopify.com"
